package dto

import "google.golang.org/grpc/metadata"

type GrantTyper interface {
	isTokenRequest_GrantType()
}

type TokenRequest struct {
	State        string
	Scope        []string
	ClientID     string
	ClientSecret string
	GrantType    GrantTyper
	Headers      metadata.MD
}

type IdentityGrant struct {
	Iss                 string
	Sub                 string
	Name                string
	GivenName           string
	MiddleName          string
	FamilyName          string
	Birthdate           string
	Zoneinfo            string
	Profile             string
	Picture             string
	Gender              string
	Locale              string
	Email               string
	EmailVerified       bool
	PhoneNumber         string
	PhoneNumberVerified bool
	Metadata            map[string]any
}

func (i *IdentityGrant) isTokenRequest_GrantType() {
}

type Code struct {
	Code string
}

func (i *Code) isTokenRequest_GrantType() {
}

type RefreshToken struct {
	RefreshToken string
}

func (i *RefreshToken) isTokenRequest_GrantType() {
}

type Authorization struct {
	Dc      int64
	Id      string
	Date    int64
	Name    string
	AppId   string
	Device  *Device
	Contact *AuthContact
	Token   *AccessToken
	Current bool
}

type Device struct {
	Id  string
	Ip  string
	App *UserAgent
}

type UserAgent struct {
	Name      string
	Version   string
	Os        string
	OsVersion string
	Device    string
	Mobile    bool
	Tablet    bool
	Desktop   bool
	Bot       bool
	String_   string
}

type AuthContact struct {
	Dc                  int64
	Id                  string
	Iss                 string
	Sub                 string
	App                 string
	Type                string
	Name                string
	GivenName           string
	MiddleName          string
	FamilyName          string
	Username            string
	Birthdate           string
	Zoneinfo            string
	Profile             string
	Picture             string
	Gender              string
	Locale              string
	Email               string
	EmailVerified       bool
	PhoneNumber         string
	PhoneNumberVerified bool
	Metadata            map[string]any
	CreatedAt           int64
	UpdatedAt           int64
	DeletedAt           int64
}

type AccessToken struct {
	TokenType    string
	AccessToken  string
	RefreshToken string
	ExpiresIn    int32
	Scope        []string
	State        string
}

// RegisterDeviceRequest represents the subscription request for PUSH notifications.
// It mirrors the structure of the gRPC RegisterDeviceRequest.
type RegisterDeviceRequest struct {
	// Push defines the PUSH notification subscription details.
	Push *PUSHSubscription
}

// RegisterDeviceResponse is the result of a successful device registration.
type RegisterDeviceResponse struct{}

// UnregisterDeviceRequest represents the request to remove a PUSH subscription.
// It mirrors the structure of the gRPC UnregisterDeviceRequest.
type UnregisterDeviceRequest struct {
	// Push defines the PUSH notification subscription to be removed.
	Push *PUSHSubscription
}

// UnregisterDeviceResponse is the result of a successful device unregistration.
type UnregisterDeviceResponse struct{}

// PUSHSubscription holds the transport-specific data for PUSH notifications.
// It corresponds to the PUSHSubscription message in the device_push.proto.
type PUSHSubscription struct {
	// Provider represents the push service provider (e.g., "fcm", "apns").
	Provider string
	// Token is the unique identifier generated by the push provider for the device.
	Token string
	// Parameters contains additional metadata required by the specific push provider.
	Parameters map[string]any
}
